import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<Image src="/vercel.svg" width={72} height={16} />
				<title>TodoList</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	)
}

export default Home
